liquid_protection:
    - BROWN_MUSHROOM
    - CARROT
    - COCOA
    - CROPS
    - MELON_STEM
    - NETHER_STALK 
    - POTATO
    - PUMPKIN_STEM
    - RED_MUSHROOM
    - SUGAR_CANE_BLOCK
    
piston_protection:
    - BROWN_MUSHROOM
    - CACTUS 
    - CARROT
    - COCOA
    - CROPS
    - MELON_BLOCK 
    - MELON_STEM
    - NETHER_STALK 
    - POTATO 
    - PUMPKIN 
    - PUMPKIN_STEM 
    - RED_MUSHROOM
    - SOIL
    - SOUL_SAND 
    - SUGAR_CANE_BLOCK  